version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870 # Web UI
      - 9000:9000 # HDFS
      - 9864:9864 # DataNode HTTP
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_dfs_webhdfs_enabled=true
      - CORE_CONF_dfs_client_use_datanode_hostname=true
      - CORE_CONF_dfs_datanode_use_datanode_hostname=true
      - CORE_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - CORE_CONF_dfs_namenode_http_address=0.0.0.0:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9865:9864 # DataNode HTTP on different host port
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_dfs_client_use_datanode_hostname=true
      - CORE_CONF_dfs_datanode_use_datanode_hostname=true
      - CORE_CONF_dfs_datanode_http_address=0.0.0.0:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoop_net

networks:
  hadoop_net:
    name: hadoop_net

volumes:
  hadoop_namenode:
  hadoop_datanode:
