services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory123
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hadoop_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "4000:3000"
    environment:
    
      MB_DB_FILE: /metabase-data/metabase.db
      
      JAVA_OPTS: "-Xmx512m"
    volumes:
      - metabase-data:/metabase-data
    networks:
      - hadoop_net
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  metabase-data:

networks:
  hadoop_net:
    external: true
