services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_DB_URI: postgresql+psycopg2://your_user:your_password@host.docker.internal:5432/your_db
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      /bin/bash -c "
      superset db upgrade &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "
